<%-- /webapp/index.jsp --%> <%@ page language="java" contentType="text/html;
charset=UTF-8" pageEncoding="UTF-8" isELIgnored="false" %> <%@ taglib
prefix="snk" uri="/WEB-INF/tld/sankhyaUtil.tld" %> <%@ page
import="br.com.sankhya.modelcore.auth.AuthenticationInfo" %>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>boilerplate-sankhya-react-vite</title>

    <!-- CSS Global -->
    <link rel="stylesheet" href="${BASE_FOLDER}/assets/index.css" />
  </head>
  <body>
    <div id="root"></div>

    <!-- Inject logged user info from Sankhya session -->
    <script type="text/javascript">
      <%
        AuthenticationInfo authInfo = (AuthenticationInfo) session.getAttribute("usuarioLogado");
        String userName = (authInfo != null) ? authInfo.getName() : "User";
        String userID = (authInfo != null) ? authInfo.getUserID().toString() : "CodeUser";
      %>
      window.sankhyaUserInfo = { name: '<%= userName %>', id: '<%= userID %>' };
    </script>

    <!-- Bundle for the application generated by Vite -->
    <script type="module" src="${BASE_FOLDER}/assets/app.js"></script>
  </body>
</html>
